// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDypMCtcl5pBpODMnoOvHtWXvNmFsQ3XAI',
    appId: '1:645515289454:web:4ea6480389e4343e70577f',
    messagingSenderId: '645515289454',
    projectId: 'voiceofpeople-369d3',
    authDomain: 'voiceofpeople-369d3.firebaseapp.com',
    storageBucket: 'voiceofpeople-369d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlwwb4jd-euTgG9B9R1g5fhdloDr_KPU',
    appId: '1:645515289454:android:d98ca14eac5ec0eb70577f',
    messagingSenderId: '645515289454',
    projectId: 'voiceofpeople-369d3',
    storageBucket: 'voiceofpeople-369d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdlSkZDDZUFCzY83VQHtQ4XmHioIByAmY',
    appId: '1:645515289454:ios:daee92149d349d4b70577f',
    messagingSenderId: '645515289454',
    projectId: 'voiceofpeople-369d3',
    storageBucket: 'voiceofpeople-369d3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdlSkZDDZUFCzY83VQHtQ4XmHioIByAmY',
    appId: '1:645515289454:ios:daee92149d349d4b70577f',
    messagingSenderId: '645515289454',
    projectId: 'voiceofpeople-369d3',
    storageBucket: 'voiceofpeople-369d3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDypMCtcl5pBpODMnoOvHtWXvNmFsQ3XAI',
    appId: '1:645515289454:web:bb7bfcd23eb634b470577f',
    messagingSenderId: '645515289454',
    projectId: 'voiceofpeople-369d3',
    authDomain: 'voiceofpeople-369d3.firebaseapp.com',
    storageBucket: 'voiceofpeople-369d3.firebasestorage.app',
  );
}
